### ISSUE TITLE
Fall 2017 Event - Preliminary Quality Review

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-tf2-ware#2]
- [ ] Update MM / SM to latest
- [ ] Make sure linux files are in `dist.linux` and that generic files are in `dist`
- [ ] Verify advertisements works
- [ ] Verify `sm_admin` works
- [ ] Verify MOTD works
- [ ] Verify your custom plugin is installed and working (dumps info to console on startup)
- [ ] Verify LL config is loading
- [ ] Verify "TF2-Ware" is working

**Comment by JustinBenedick** [comment]
Updates sm/mm and sorted files 24e55776b2c7ce7cc6af01ee3a8572e10443ce4b

**Comment by dudleycodes** [comment]
@JustinBenedick how's this going?

**Comment by dudleycodes** [comment]
What's the word on this @JustinBenedick?

**Comment by JustinBenedick** [comment]
tf2 ware doesn't work,  event is over
